/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 153
#define YY_END_OF_BUFFER 154
static yyconst short int yy_accept[549] =
    {   0,
        0,    0,  154,  152,  151,  151,  151,  152,  152,  112,
      130,  132,  152,  106,  107,  128,  126,  147,  127,  146,
      129,   98,   98,  148,  149,  141,  113,  142,  150,  152,
      108,  109,  136,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  110,  133,  111,  131,  151,  151,  151,
      140,    0,  104,    0,  118,  135,  119,    0,    0,  116,
      124,  114,  125,  115,  145,    0,    0,  117,    0,    0,
        0,   98,  137,  143,  139,  144,  138,   97,  121,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,

       97,   97,   34,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   47,   97,   97,   97,   97,   97,   97,   97,
       97,   59,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,  120,  134,    0,  105,    0,    0,    0,    0,  102,
       99,  101,  100,  122,  123,    0,    3,    5,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   44,    0,    0,    0,   49,    0,    0,    0,   53,
        0,   55,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   83,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   95,    0,    0,  103,  102,  102,
        0,    0,    0,    0,    9,    0,    0,   12,    0,   14,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   37,   38,    0,    0,    0,
        0,    0,    0,   46,    0,   50,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   79,
        0,    0,   82,    0,    0,    0,    0,    0,   91,    0,

        0,    0,    0,    0,   99,    0,    0,    0,    0,   11,
       13,   15,    0,    0,    0,   20,    0,    0,    0,   21,
        0,   23,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   42,   43,    0,    0,    0,    0,    0,    0,    0,
        0,   60,    0,    0,    0,    0,    0,    0,    0,    0,
       69,    0,    0,    0,    0,    0,    0,    0,    0,   81,
        0,    0,    0,   87,    0,   89,    0,    0,    0,   94,
        0,    0,    0,    4,    0,   10,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   33,   35,
        0,    0,   40,   41,   45,   48,    0,    0,    0,   56,

        0,    0,    0,    0,   63,    0,    0,    0,    0,   68,
       70,   71,   72,   75,   76,    0,    0,    0,    0,   85,
        0,    0,    0,    0,    0,   96,    1,    2,    0,    0,
        0,   17,    0,    0,    0,   22,    0,    0,    0,    0,
        0,   32,    0,    0,   51,    0,    0,   57,    0,   61,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   84,
        0,    0,   90,    0,   93,    0,    0,   18,   19,   28,
        0,   30,    0,    0,    0,   27,   31,    0,   39,    0,
       54,   58,    0,   64,   65,    0,   67,    0,    0,    0,
       78,    0,   86,   88,   92,    0,    0,    0,   29,    0,

       24,   25,    0,   52,   62,    0,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   74,    0,    0,    0,
        0,    0,   36,    0,    0,   77,   80,    6,    7,    0,
        0,   73,    0,    0,    8,    0,   66,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   24,   25,   24,   26,   24,   27,   28,   29,
       30,   31,   32,    1,   33,   33,   33,   33,   34,   33,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   35,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    4,    4,    5,    1,    1,    1,    1,    5,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[560] =
    {   0,
        0,    0,  676,  677,   68,   72,   76,  645,   75,  677,
      644,   73,  636,  677,  677,  642,   69,  677,   70,  677,
       72,   67,   72,  677,  677,   59,  641,   74,  677,    0,
      677,  677,  640,   55,   62,   69,   73,   71,   84,  615,
       75,  614,  607,   88,   88,   79,  621,   98,  104,   73,
      101,  108,  611,  677,   77,  677,  677,  161,  167,  171,
      677,  146,  677,  147,  677,  677,  677,  653,  170,  677,
      677,  677,  677,  677,  677,  166,    0,  677,  171,  138,
        0,  191,  633,  677,  677,  677,  632,  677,  677,  612,
      616,  607,  604,  598,  597,  601,  609,  120,  612,  611,

      146,  175,  591,  597,  591,  588,  146,  596,  592,  588,
      595,  584,  677,   81,  589,  582,  588,  577,  143,  587,
      592,  596,  133,  593,  185,  580,  172,  167,  584,  579,
      579,  132,  175,  575,  187,  580,  571,  171,  579,  577,
      568,  677,  677,    0,  677,    0,  211,  224,  228,  245,
      230,  237,    0,  677,  677,  577,  583,  677,  570,  567,
      205,  569,  578,  573,  574,  559,  557,  219,  559,  219,
      562,  571,  566,  568,  568,  563,  555,  212,  561,  547,
      563,  677,  558,  548,  552,  677,  553,  558,  553,  677,
      534,  556,  544,  537,  548,  531,  532,  539,  538,  539,

      534,  526,  525,  527,  530,  537,  522,  520,  520,  535,
      522,  518,  216,  530,  677,  529,  519,  523,  518,  511,
      525,  527,  526,  515,  525,    0,    0,  677,  677,  561,
      264,  510,  517,  512,  677,  507,  502,  677,  508,  677,
      509,  246,  498,  493,  509,  504,  501,  506,  491,  500,
      489,  487,  487,  494,  492,  677,  677,  494,  485,  484,
      495,  480,  485,  677,  484,  677,  494,  477,  491,  488,
      477,  490,  474,  488,  483,  478,  481,  467,  465,  474,
      465,  462,  475,  465,  469,  474,  473,  467,  463,  677,
      472,  450,  677,  247,  458,  463,  462,  448,  677,  448,

      449,  460,  459,  281,  288,  239,  447,  459,  457,  677,
      677,  677,  475,  477,  458,  677,  456,  437,  450,  677,
      439,  228,  440,  428,  440,  445,  444,  439,  444,  427,
      432,  677,  677,  440,  438,  431,  426,  435,  423,  419,
      418,  677,  417,  432,  431,  410,  413,  426,  413,  416,
      677,  424,  421,  423,  406,  416,  406,  421,  417,  677,
      415,  415,  417,  677,  404,  677,  415,  406,  414,  677,
      397,  394,  405,  677,  410,  677,  409,  408,  388,  397,
      385,  393,  384,  399,  231,  381,  385,  380,  677,  677,
      395,  388,  677,  677,  677,  677,  391,  394,  379,  677,

      376,  378,  386,  371,  677,  374,  383,  370,  381,  677,
      677,  677,  385,  677,  677,  370,  364,  382,  375,  677,
      368,  374,  367,  366,  357,  677,  677,  677,  272,  356,
      355,  677,  354,  355,  367,  677,  369,  368,  353,  362,
      361,  677,  365,  345,  677,  360,  343,  677,  344,  677,
      355,  342,  341,  342,  338,  254,  342,  349,  342,  677,
      347,  347,  677,  345,  677,  275,  335,  677,  677,  677,
      335,  677,  329,  335,  328,  677,  677,  341,  677,  338,
      677,  677,  338,  677,  677,  324,  677,  322,  338,  329,
      677,  323,  677,  677,  677,  323,  323,  329,  677,  314,

      677,  677,  331,  677,  677,  326,  312,  311,  303,  324,
      323,  313,  301,  677,  305,  303,  316,  301,  314,  317,
      312,  299,  294,  269,  287,  269,  677,  280,  272,  271,
      262,  275,  677,  276,  259,  677,  677,  677,  677,  262,
      258,  677,  239,  224,  677,  215,  677,  677,  329,  334,
      336,  341,  346,  267,  261,  236,  351,  224,  199
    } ;

static yyconst short int yy_def[560] =
    {   0,
      548,    1,  548,  548,  548,  548,  548,  548,  549,  548,
      548,  548,  550,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  551,
      548,  548,  548,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  548,  548,  548,  548,  548,  548,  548,
      548,  549,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  552,  553,  548,  548,  548,
      554,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  555,  548,  556,  552,  557,  552,  553,
      548,  548,  554,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  558,  559,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,    0,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548
    } ;

static yyconst short int yy_nxt[747] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   23,   23,   23,   23,   23,   24,   25,   26,   27,
       28,   29,   30,   30,   30,   31,    4,   32,   33,   30,
       34,   35,   36,   37,   38,   39,   40,   30,   41,   30,
       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   53,   30,   30,   54,   55,   56,   57,   58,
       58,   59,   58,   58,   58,   59,   58,   58,   60,   59,
       58,   63,   66,   71,   79,   76,   73,   83,   84,   79,
       77,   82,   82,   82,   82,   82,   82,   82,   72,   74,

       75,   78,   67,   86,   87,   90,  142,   91,   80,   98,
       95,   64,   92,   93,   94,   96,   99,  102,   97,  100,
      113,  105,  101,  106,  108,  135,  103,  114,  117,   81,
      136,  185,  118,  107,  109,  123,  104,  110,  124,  186,
      111,  119,  121,  143,  122,  126,  127,  120,  131,  137,
      139,  132,   63,   62,  138,  140,  128,  152,  152,  129,
      133,  130,   58,   58,   59,   58,   62,  134,   58,   60,
       59,   58,   58,   58,   59,   58,   68,  164,  165,  148,
      212,  196,   64,   62,  149,  168,  197,  191,  213,   68,
      151,  151,  151,  151,  151,  151,  151,  169,  170,   62,

      178,  192,   68,   62,  179,   62,   68,  207,   79,  144,
       82,   82,   82,   82,   82,   82,   82,  171,  205,  221,
      172,  222,   68,  208,  148,  173,   68,   62,   68,  149,
      199,  200,  146,  201,  214,  217,  206,  148,  215,  227,
      202,  148,  228,  203,  218,  236,  149,  229,  230,  151,
      151,  151,  151,  151,  151,  151,  152,  152,  237,  244,
      291,  248,  258,  231,  226,  259,  313,  384,  314,  292,
      153,  315,  385,  547,  231,  245,  249,  250,  304,  372,
      304,  546,  246,  305,  305,  305,  305,  305,  305,  305,
      361,  438,  373,  439,  488,  362,  489,  545,  544,  363,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  466,  496,  543,  542,  541,  540,
      539,  538,  537,  536,  467,  535,  534,  533,  497,   62,
       62,   62,   62,   62,   68,   68,  532,   68,   68,   88,
       88,  147,  147,  147,  147,  147,  150,  531,  150,  150,
      150,  149,  149,  149,  149,  149,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  511,  510,  509,  508,  507,
      506,  505,  504,  503,  502,  501,  500,  499,  498,  495,
      494,  493,  492,  491,  490,  487,  486,  485,  484,  483,

      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  383,  382,  381,  380,  379,  378,  377,

      376,  375,  374,  371,  370,  369,  368,  367,  366,  365,
      364,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  312,  311,  310,  309,
      308,  307,  306,  229,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,

      265,  264,  263,  262,  261,  260,  257,  256,  255,  254,
      253,  252,  251,  247,  243,  242,  241,  240,  239,  238,
      235,  234,  233,  232,  225,  224,  223,  220,  219,  216,
      211,  210,  209,  204,  198,  195,  194,  193,  190,  189,
      188,  187,  184,  183,  182,  181,  180,  177,  176,  175,
      174,  167,  166,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  145,  141,  125,  116,  115,  112,   89,
       85,   70,   69,   65,   61,  548,    3,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548
    } ;

static yyconst short int yy_chk[747] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    6,    6,    6,    6,    7,    7,    7,
        7,    9,   12,   17,   22,   21,   19,   26,   26,   23,
       21,   23,   23,   23,   23,   23,   23,   23,   17,   19,

       19,   21,   12,   28,   28,   34,   55,   34,   22,   36,
       35,    9,   34,   34,   34,   35,   36,   37,   35,   36,
       41,   38,   36,   38,   39,   50,   37,   41,   44,   22,
       50,  114,   44,   38,   39,   46,   37,   39,   46,  114,
       39,   44,   45,   55,   45,   48,   48,   44,   49,   51,
       52,   49,   62,   64,   51,   52,   48,   80,   80,   48,
       49,   48,   58,   58,   58,   58,   64,   49,   59,   59,
       59,   59,   60,   60,   60,   60,   69,   98,   98,   76,
      132,  123,   62,   64,   76,  101,  123,  119,  132,   69,
       79,   79,   79,   79,   79,   79,   79,  101,  101,   64,

      107,  119,  559,   64,  107,   64,   69,  128,   82,   64,
       82,   82,   82,   82,   82,   82,   82,  102,  127,  138,
      102,  138,   69,  128,  147,  102,   69,  558,   69,  147,
      125,  125,   69,  125,  133,  135,  127,  148,  133,  556,
      125,  149,  148,  125,  135,  161,  149,  150,  150,  151,
      151,  151,  151,  151,  151,  151,  152,  152,  161,  168,
      213,  170,  178,  151,  555,  178,  242,  322,  242,  213,
      554,  242,  322,  546,  151,  168,  170,  170,  231,  306,
      231,  544,  168,  231,  231,  231,  231,  231,  231,  231,
      294,  385,  306,  385,  456,  294,  456,  543,  541,  294,

      304,  304,  304,  304,  304,  304,  304,  305,  305,  305,
      305,  305,  305,  305,  429,  466,  540,  535,  534,  532,
      531,  530,  529,  528,  429,  526,  525,  524,  466,  549,
      549,  549,  549,  549,  550,  550,  523,  550,  550,  551,
      551,  552,  552,  552,  552,  552,  553,  522,  553,  553,
      553,  557,  557,  557,  557,  557,  521,  520,  519,  518,
      517,  516,  515,  513,  512,  511,  510,  509,  508,  507,
      506,  503,  500,  498,  497,  496,  492,  490,  489,  488,
      486,  483,  480,  478,  475,  474,  473,  471,  467,  464,
      462,  461,  459,  458,  457,  455,  454,  453,  452,  451,

      449,  447,  446,  444,  443,  441,  440,  439,  438,  437,
      435,  434,  433,  431,  430,  425,  424,  423,  422,  421,
      419,  418,  417,  416,  413,  409,  408,  407,  406,  404,
      403,  402,  401,  399,  398,  397,  392,  391,  388,  387,
      386,  384,  383,  382,  381,  380,  379,  378,  377,  375,
      373,  372,  371,  369,  368,  367,  365,  363,  362,  361,
      359,  358,  357,  356,  355,  354,  353,  352,  350,  349,
      348,  347,  346,  345,  344,  343,  341,  340,  339,  338,
      337,  336,  335,  334,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  321,  319,  318,  317,  315,  314,  313,

      309,  308,  307,  303,  302,  301,  300,  298,  297,  296,
      295,  292,  291,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  265,  263,  262,  261,
      260,  259,  258,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  241,  239,  237,  236,
      234,  233,  232,  230,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  214,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  189,  188,  187,

      185,  184,  183,  181,  180,  179,  177,  176,  175,  174,
      173,  172,  171,  169,  167,  166,  165,  164,  163,  162,
      160,  159,  157,  156,  141,  140,  139,  137,  136,  134,
      131,  130,  129,  126,  124,  122,  121,  120,  118,  117,
      116,  115,  112,  111,  110,  109,  108,  106,  105,  104,
      103,  100,   99,   97,   96,   95,   94,   93,   92,   91,
       90,   87,   83,   68,   53,   47,   43,   42,   40,   33,
       27,   16,   13,   11,    8,    3,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grammar.l"
#define INITIAL 0
#line 2 "grammar.l"
  extern int yylex();}
#line 715 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 5 "grammar.l"

#line 868 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 549 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 677 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 6 "grammar.l"
{acc++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 7 "grammar.l"
{acc++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 8 "grammar.l"
{acc++;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 9 "grammar.l"
{acc++;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 10 "grammar.l"
{acc++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 11 "grammar.l"
{acc++;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 12 "grammar.l"
{acc++;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 13 "grammar.l"
{acc++;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 14 "grammar.l"
{acc++;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 15 "grammar.l"
{acc++;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 16 "grammar.l"
{acc++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 17 "grammar.l"
{acc++;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 18 "grammar.l"
{acc++;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 19 "grammar.l"
{acc++;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 20 "grammar.l"
{acc++;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 21 "grammar.l"
{acc++;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 22 "grammar.l"
{acc++;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 23 "grammar.l"
{acc++;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 24 "grammar.l"
{acc++;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 25 "grammar.l"
{acc++;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 26 "grammar.l"
{acc++;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 27 "grammar.l"
{acc++;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 28 "grammar.l"
{acc++;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 29 "grammar.l"
{acc++;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 30 "grammar.l"
{acc++;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 31 "grammar.l"
{acc++;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 32 "grammar.l"
{acc++;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 33 "grammar.l"
{acc++;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 34 "grammar.l"
{acc++;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 35 "grammar.l"
{acc++;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 36 "grammar.l"
{acc++;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 37 "grammar.l"
{acc++;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 38 "grammar.l"
{acc++;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 39 "grammar.l"
{acc++;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 40 "grammar.l"
{acc++;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 41 "grammar.l"
{acc++;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 42 "grammar.l"
{acc++;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 43 "grammar.l"
{acc++;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 44 "grammar.l"
{acc++;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 45 "grammar.l"
{acc++;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 46 "grammar.l"
{acc++;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 47 "grammar.l"
{acc++;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 48 "grammar.l"
{acc++;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 49 "grammar.l"
{acc++;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 50 "grammar.l"
{acc++;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 51 "grammar.l"
{acc++;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 52 "grammar.l"
{acc++;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 53 "grammar.l"
{acc++;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 54 "grammar.l"
{acc++;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 55 "grammar.l"
{acc++;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 56 "grammar.l"
{acc++;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 57 "grammar.l"
{acc++;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 58 "grammar.l"
{acc++;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 59 "grammar.l"
{acc++;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 60 "grammar.l"
{acc++;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 61 "grammar.l"
{acc++;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 62 "grammar.l"
{acc++;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 63 "grammar.l"
{acc++;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 64 "grammar.l"
{acc++;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 65 "grammar.l"
{acc++;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 66 "grammar.l"
{acc++;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 67 "grammar.l"
{acc++;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 68 "grammar.l"
{acc++;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 69 "grammar.l"
{acc++;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 70 "grammar.l"
{acc++;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 71 "grammar.l"
{acc++;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 72 "grammar.l"
{acc++;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 73 "grammar.l"
{acc++;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 74 "grammar.l"
{acc++;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 75 "grammar.l"
{acc++;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 76 "grammar.l"
{acc++;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 77 "grammar.l"
{acc++;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 78 "grammar.l"
{acc++;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 79 "grammar.l"
{acc++;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 80 "grammar.l"
{acc++;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 81 "grammar.l"
{acc++;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 82 "grammar.l"
{acc++;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 83 "grammar.l"
{acc++;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 84 "grammar.l"
{acc++;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 85 "grammar.l"
{acc++;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 86 "grammar.l"
{acc++;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 87 "grammar.l"
{acc++;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 88 "grammar.l"
{acc++;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 89 "grammar.l"
{acc++;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 90 "grammar.l"
{acc++;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 91 "grammar.l"
{acc++;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 92 "grammar.l"
{acc++;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 93 "grammar.l"
{acc++;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 94 "grammar.l"
{acc++;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 95 "grammar.l"
{acc++;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 96 "grammar.l"
{acc++;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 97 "grammar.l"
{acc++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 98 "grammar.l"
{acc++;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 99 "grammar.l"
{acc++;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 100 "grammar.l"
{acc++;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 101 "grammar.l"
{acc++;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 103 "grammar.l"
{acc++;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 105 "grammar.l"
{acc++;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 106 "grammar.l"
{acc++;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 107 "grammar.l"
{acc++;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 108 "grammar.l"
{acc++;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 110 "grammar.l"
{acc++;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 111 "grammar.l"
{acc++;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 113 "grammar.l"
{acc++;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 114 "grammar.l"
{acc++;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 116 "grammar.l"
{acc++;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 117 "grammar.l"
{acc++;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 118 "grammar.l"
{acc++;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 119 "grammar.l"
{acc++;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 120 "grammar.l"
{acc++;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 121 "grammar.l"
{acc++;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 123 "grammar.l"
{acc++;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 125 "grammar.l"
{acc++;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 126 "grammar.l"
{acc++;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 127 "grammar.l"
{acc++;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 128 "grammar.l"
{acc++;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 129 "grammar.l"
{acc++;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 130 "grammar.l"
{acc++;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 131 "grammar.l"
{acc++;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 132 "grammar.l"
{acc++;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 133 "grammar.l"
{acc++;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 134 "grammar.l"
{acc++;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 135 "grammar.l"
{acc++;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 137 "grammar.l"
{acc++;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 138 "grammar.l"
{acc++;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 140 "grammar.l"
{acc++;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 141 "grammar.l"
{acc++;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 142 "grammar.l"
{acc++;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 143 "grammar.l"
{acc++;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 144 "grammar.l"
{acc++;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 145 "grammar.l"
{acc++;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 146 "grammar.l"
{acc++;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 147 "grammar.l"
{acc++;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 148 "grammar.l"
{acc++;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 149 "grammar.l"
{acc++;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 150 "grammar.l"
{acc++;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 151 "grammar.l"
{acc++;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 152 "grammar.l"
{acc++;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 154 "grammar.l"
{acc++;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 155 "grammar.l"
{acc++;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 156 "grammar.l"
{acc++;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 157 "grammar.l"
{acc++;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 158 "grammar.l"
{acc++;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 159 "grammar.l"
{acc++;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 161 "grammar.l"
{acc++;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 162 "grammar.l"
{acc++;}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 163 "grammar.l"
{acc++;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 164 "grammar.l"
{acc++;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 165 "grammar.l"
{acc++;}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 166 "grammar.l"
{acc++;}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 168 "grammar.l"
{acc++;}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 170 "grammar.l"
{acc++;}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 172 "grammar.l"
ECHO;
	YY_BREAK
#line 1716 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 549 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 549 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 548);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 172 "grammar.l"

